FROM golang:1.23-alpine

WORKDIR /workspace

RUN apk add --no-cache ca-certificates git

COPY go.* ./
RUN go mod download

ENV CGO_ENABLED=0
ENV GOFLAGS=-buildvcs=false

CMD ["go", "run", "-a", "-mod=mod", "./cmd/server"]
